[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['cd backend && pip install -r requirements.txt']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'cd backend && uvicorn src:app --host 0.0.0.0 --port $PORT'
