"""Fix community model foreign keys

Revision ID: 0ae04efe1de6
Revises: f77c54bd4029
Create Date: 2025-06-23 00:30:08.054239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ae04efe1de6'
down_revision: Union[str, None] = 'f77c54bd4029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'fk_posts_user_id_users_uid',
        'posts', 'users',
        ['user_id'], ['uid'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_comments_post_id_posts_id',
        'comments', 'posts',
        ['post_id'], ['id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_comments_user_id_users_uid',
        'comments', 'users',
        ['user_id'], ['uid'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_likes_user_id_users_uid',
        'likes', 'users',
        ['user_id'], ['uid'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_likes_post_id_posts_id',
        'likes', 'posts',
        ['post_id'], ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_likes_post_id_posts_id', 'likes', type_='foreignkey')
    op.drop_constraint('fk_likes_user_id_users_uid', 'likes', type_='foreignkey')
    op.drop_constraint('fk_comments_user_id_users_uid', 'comments', type_='foreignkey')
    op.drop_constraint('fk_comments_post_id_posts_id', 'comments', type_='foreignkey')
    op.drop_constraint('fk_posts_user_id_users_uid', 'posts', type_='foreignkey')
    # ### end Alembic commands ###
