"""user update

Revision ID: 5265d271f294
Revises: 90d78306b5fe
Create Date: 2025-06-22 22:17:43.450532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5265d271f294'
down_revision: Union[str, None] = '90d78306b5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat_messages', ['id'])
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_constraint(None, 'chat_messages', type_='unique')
    # ### end Alembic commands ###
    
